name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
        
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y cmake
        sudo apt-get install rpm
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Create ubuntu package
      working-directory: ${{github.workspace}}/build
      if: matrix.os == 'ubuntu-latest'
      run: |
        cpack -G "DEB"
        cpack -G "RPM"
        
    - name: Create window package
      working-directory: ${{github.workspace}}/build
      if: matrix.os == 'windows-latest'
      run: cpack -G "WIX"

    - name: Create macos package
      working-directory: ${{github.workspace}}/build
      if: matrix.os == 'macos-latest'
      run: cpack -G "DragNDrop"

    - name: Upload ubuntu artifact
      uses: actions/upload-artifact@v4
      
      if: matrix.os == 'ubuntu-latest'
      with:
          name: ${{ matrix.os }}-dz06-pack
          path: |
            build/*.deb
            build/*.rpm

    - name: Upload window artifact
      uses: actions/upload-artifact@v4

      if: matrix.os == 'windows-latest'
      with:
          name: ${{ matrix.os }}-dz06-pack
          path: build/*.wix

    - name: Upload macos artifact
      uses: actions/upload-artifact@v4

      if: matrix.os == 'macos-latest'
      with:
          name: ${{ matrix.os }}-dz06-pack
          path: build/*.dmg

